name: "Generate the contribution graph"

on:
  # schedule:
    # - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: "Generate the contribution graph"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install lld"
        run: sudo apt-get install -y lld
      - name: "Install rust"
        run: rustup update nightly && rustup default nightly
      - name: "Generate the contribution graph"
        run: cargo run
        working-directory: ./contrib-graph
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: dnbln
          FAIL_IF_ZERO: true
      - name: "Commit and push"
        run: |
          git config --local user.name "Dinu Blanovschi"
          git config --local user.email "git@dnbln.dev"
          git add contrib-graph/3d-contrib-plot.svg
          git commit -m "Update the graph"
          git push origin main
